[env]
TERM = "xterm-256color"

[font]
size = 20

normal.family = "JetBrainsMono Nerd Font"

[window]
# dimensions = { columns = 100, lines = 24 }
padding = { x = 5, y = 2 }
# position = { x = 756, y = 491}
startup_mode = "Maximized"

option_as_alt = "Both"

[general]
import = [ "~/.config/alacritty/tokyo-night.toml" ]

[scrolling]
history = 1000
